import { db } from '@/db';
import { bookings } from '@/db/schema';

async function main() {
    const now = new Date();
    
    const getDaysAgo = (days: number): string => {
        const date = new Date(now);
        date.setDate(date.getDate() - days);
        return date.toISOString();
    };
    
    const getDaysFromNow = (days: number): string => {
        const date = new Date(now);
        date.setDate(date.getDate() + days);
        return date.toISOString();
    };

    const sampleBookings = [
        {
            userId: 1,
            addressId: 1,
            serviceType: 'plumber',
            subService: 'Leaky Faucet Repair',
            workDescription: 'Kitchen sink faucet is leaking water continuously',
            photoUrl: null,
            status: 'completed',
            professionalName: 'Ramesh Singh',
            professionalContact: '9876540001',
            bookingDate: getDaysAgo(20),
            completionDate: getDaysAgo(19),
            createdAt: getDaysAgo(20),
        },
        {
            userId: 1,
            addressId: 1,
            serviceType: 'electrician',
            subService: 'Light Fixture Install',
            workDescription: 'Need to install 3 ceiling lights in living room',
            photoUrl: null,
            status: 'completed',
            professionalName: 'Vijay Kumar',
            professionalContact: '9876540002',
            bookingDate: getDaysAgo(15),
            completionDate: getDaysAgo(14),
            createdAt: getDaysAgo(15),
        },
        {
            userId: 1,
            addressId: 2,
            serviceType: 'carpenter',
            subService: 'Furniture Assembly',
            workDescription: 'Office desk and chair assembly required',
            photoUrl: null,
            status: 'completed',
            professionalName: 'Suresh Yadav',
            professionalContact: '9876540003',
            bookingDate: getDaysAgo(10),
            completionDate: getDaysAgo(9),
            createdAt: getDaysAgo(10),
        },
        {
            userId: 2,
            addressId: 4,
            serviceType: 'plumber',
            subService: 'Drain Cleaning',
            workDescription: 'Bathroom drain is clogged, water not draining',
            photoUrl: null,
            status: 'in_progress',
            professionalName: 'Mohan Reddy',
            professionalContact: '9876540004',
            bookingDate: getDaysAgo(3),
            completionDate: null,
            createdAt: getDaysAgo(4),
        },
        {
            userId: 2,
            addressId: 4,
            serviceType: 'househelp',
            subService: 'Deep Cleaning',
            workDescription: 'Full house deep cleaning required before festival',
            photoUrl: null,
            status: 'confirmed',
            professionalName: 'Lakshmi Devi',
            professionalContact: '9876540005',
            bookingDate: getDaysFromNow(2),
            completionDate: null,
            createdAt: getDaysAgo(1),
        },
        {
            userId: 3,
            addressId: 6,
            serviceType: 'electrician',
            subService: 'Wiring Repair',
            workDescription: 'Multiple power outlets not working in bedroom',
            photoUrl: null,
            status: 'completed',
            professionalName: 'Anil Sharma',
            professionalContact: '9876540006',
            bookingDate: getDaysAgo(12),
            completionDate: getDaysAgo(11),
            createdAt: getDaysAgo(12),
        },
        {
            userId: 3,
            addressId: 6,
            serviceType: 'painter',
            subService: 'Interior Painting',
            workDescription: 'Living room and 2 bedrooms need fresh paint',
            photoUrl: null,
            status: 'pending',
            professionalName: null,
            professionalContact: null,
            bookingDate: getDaysFromNow(5),
            completionDate: null,
            createdAt: getDaysAgo(2),
        },
        {
            userId: 4,
            addressId: 9,
            serviceType: 'carpenter',
            subService: 'Door Repair',
            workDescription: 'Bedroom door hinges broken, door not closing properly',
            photoUrl: null,
            status: 'completed',
            professionalName: 'Raju Carpenter',
            professionalContact: '9876540007',
            bookingDate: getDaysAgo(8),
            completionDate: getDaysAgo(7),
            createdAt: getDaysAgo(8),
        },
        {
            userId: 4,
            addressId: 9,
            serviceType: 'househelp',
            subService: 'Regular Cleaning',
            workDescription: 'Weekly cleaning service',
            photoUrl: null,
            status: 'confirmed',
            professionalName: 'Geeta Bai',
            professionalContact: '9876540008',
            bookingDate: getDaysFromNow(1),
            completionDate: null,
            createdAt: getDaysAgo(3),
        },
        {
            userId: 5,
            addressId: 11,
            serviceType: 'plumber',
            subService: 'Pipe Installation',
            workDescription: 'New washing machine water pipe installation',
            photoUrl: null,
            status: 'completed',
            professionalName: 'Santosh Kumar',
            professionalContact: '9876540009',
            bookingDate: getDaysAgo(6),
            completionDate: getDaysAgo(5),
            createdAt: getDaysAgo(6),
        },
        {
            userId: 1,
            addressId: 1,
            serviceType: 'electrician',
            subService: 'Fuse Box Check',
            workDescription: 'Power tripping frequently, need fuse box inspection',
            photoUrl: null,
            status: 'pending',
            professionalName: null,
            professionalContact: null,
            bookingDate: now.toISOString(),
            completionDate: null,
            createdAt: now.toISOString(),
        },
        {
            userId: 2,
            addressId: 5,
            serviceType: 'carpenter',
            subService: 'Custom Shelving',
            workDescription: 'Need custom wall shelves in study room',
            photoUrl: null,
            status: 'cancelled',
            professionalName: null,
            professionalContact: null,
            bookingDate: getDaysAgo(5),
            completionDate: null,
            createdAt: getDaysAgo(7),
        },
        {
            userId: 3,
            addressId: 7,
            serviceType: 'painter',
            subService: 'Exterior Painting',
            workDescription: 'Balcony walls exterior painting',
            photoUrl: null,
            status: 'completed',
            professionalName: 'Pappu Painter',
            professionalContact: '9876540010',
            bookingDate: getDaysAgo(18),
            completionDate: getDaysAgo(16),
            createdAt: getDaysAgo(18),
        },
        {
            userId: 4,
            addressId: 10,
            serviceType: 'househelp',
            subService: 'Laundry',
            workDescription: 'Dry cleaning and ironing services',
            photoUrl: null,
            status: 'in_progress',
            professionalName: 'Meena Bai',
            professionalContact: '9876540011',
            bookingDate: getDaysAgo(1),
            completionDate: null,
            createdAt: getDaysAgo(1),
        },
        {
            userId: 5,
            addressId: 11,
            serviceType: 'painter',
            subService: 'Touch-ups',
            workDescription: 'Wall paint touch-ups after furniture rearrangement',
            photoUrl: null,
            status: 'pending',
            professionalName: null,
            professionalContact: null,
            bookingDate: getDaysFromNow(3),
            completionDate: null,
            createdAt: now.toISOString(),
        },
    ];

    await db.insert(bookings).values(sampleBookings);
    
    console.log('✅ Bookings seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});